# DrPower机械臂MoveIt2配置
# 关节限制配置

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    
  joint2:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    
  joint3:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    
  joint4:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 8.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    
  joint5:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 8.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    
  joint6:
    has_velocity_limits: true
    max_velocity: 3.0
    has_acceleration_limits: true
    max_acceleration: 8.0
    has_jerk_limits: false
    max_jerk: 0.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
