# 统一串口管理节点专用配置文件
# 用于单独调试底盘和云台功能
unified_serial_manager:
  ros__parameters:
    # === 串口配置 ===
    serial_port: "/dev/ttyTHS1"        # 串口设备路径 (/dev/ttyTHS0, /dev/ttyUSB0, /dev/ttyACM0)
    baud_rate: 115200                  # 波特率
    timeout: 1.0                       # 串口超时时间(秒)
    
    # === 里程计相关配置 ===
    odom_frame_id: "odom"             # 里程计坐标系ID
    base_frame_id: "base_link"        # 机器人基础坐标系ID
    publish_tf: false                   # 是否发布TF变换
    
    # === 云台相关配置 ===
    publish_gimbal_feedback: true      # 是否发布云台角度反馈
    
    # === 控制超时配置 ===
    cmd_vel_timeout: 2.0              # 底盘速度命令超时时间(秒)，超时后自动停止
    gimbal_cmd_timeout: 5.0           # 云台角度命令超时时间(秒)
    
    # === 调试选项 ===
    # 注意：下面的选项需要在代码中实现
    # debug_mode: false                # 是否启用调试模式
    # log_received_data: false         # 是否记录接收到的原始数据
    # log_sent_commands: false         # 是否记录发送的命令
